{
  try {
    connect(userId,password);
  }
 catch (  XMPPException xmppe1) {
    String message=xmppe1.getMessage();
    if (Validator.isNotNull(message) && message.contains("not-authorized")) {
      if (_log.isDebugEnabled()) {
        _log.debug("Importing user " + userId + " because he cannot connect to Jabber");
      }
      try {
        importUser(userId,password);
        connect(userId,password);
      }
 catch (      XMPPException xmppe2) {
        if (message.contains("conflict(409)")) {
          _log.error("User " + userId + "already exists but password "+ "is not synchronized with Jabber");
        }
      }
catch (      Exception e) {
        _log.error(e,e);
      }
    }
  }
catch (  Exception e) {
    _log.error(e,e);
  }
}
